brush creation app local working
net-art-uchicago/collaborative-artware pull request #48
Opened 2021-05-13 18:00 UTC by tovarm-uchi

- html code for settings, left toolbox (empty for now), 2 canvas and brush section
- creates two p5.js canvas: one for drawing and one for testing. 
- clear option to clear the canvas
- Saving input to store the image as a base64 encoding (not push/get yet) under the brush section
- Have 4 default brushes to help make drawing

2021-05-15 17:02 UTC, nbriz requested changes
this looks great Melissa! love where this is heading, lots of cool ideas here, i like how meta this can get by allowing the brush u create to become an input for another brush! i've left some specific comments below, but i also have a few general comments:

**coding style**: don't forget that we're conforming to the [StandardJS](https://standardjs.com/) coding style. if u haven't already i suggest adding the standard [plugin](https://standardjs.com/#are-there-text-editor-plugins) to ur editor so u can lint ur js files as u work. there are lots of linting/style issues in ur JavaScript files.

**reorganize code**: u've got global variables being declared throughout ur main.js function, to keep the code a bit more readable it's best to declare all the global variables at the top of the file

**function syntax**: at the moment u're mixing function declaration styles in ur global code. sometimes u do `const name = function ()` other times `function name ()`, both are valid, but for readability it's best to pick one && keep ur code consistent.

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/index.html
> +    <script src="js/myLine.js"></script>
it's best to import ur js files below all ur other HTML elements (just above the closing `<body>` element) that way u make sure the page has loaded all ur HTML elements before any of ur JS code tries to interact w/them

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/index.html
> +      </div>
what is `leftContainer` used for? it's not immediately obvious to me? am i missing something?

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/index.html
> +          </div>
let's try to keep the syntax/spacing a bit more consistent throughout the HTML `attribute="value"` rather than `attribute = "value"` or `attribute= "value"` etc.

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/index.html
> +        <input type="text" id="bname" name="bname" value="Enter Brush Name"><br>
when u want to communicate what an input element is for w/in the input itself u should use the `placeholder="Enter Brush Name"` rather than `value="Enter Brush Name"`, this can also help u write some "validation" code later, b/c the placeholder doesn't effect the element's `.value` property, which means when the user tires to save a brush u can check to to see if `ele.value === ''` && if it is equal to an empty string than u know they haven't given it a name yet && u can display a warning, otherwise u'd create the new brush

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/index.html
> +      <button id="clear">Clear</button>
it might be helpful to have 2 different clear buttons, one for each canvas

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/js/main.js
> +var defaultBrushes = [
I like the system u've got going here for managing brushes! very nice! i can imagine this growing in complexity as the project changes, so what about creating a separate `BrushManager.js` class which u can use to abstract all the logic related to managing brushes?

2021-05-15 17:02 UTC, nbriz commented on public/brush-creator/js/main.js
> +      }
even though it's conceptually simple, in practice it can be tricky to figure out how best to create a "line brush" (as u might have realized when u started working on this), creating a separate class to handle that logic (as u did) is a great idea && ur approach to figuring out is definitely clever! ...but it's got a few bugs, including this one:

https://user-images.githubusercontent.com/2506806/118371911-62010580-b574-11eb-9740-2aab5430ea95.mp4

but as u might imagine, this is an issue lots of folks creating drawing apps have had to figure out && there's a pretty common/conventional pattern for how to accomplish this. i created a simple example where i've implemented this conventional pattern using p5js for u to consider >> https://jsfiddle.net/azynh5b7/

2021-05-19 16:25 UTC, tovarm-uchi commented on public/brush-creator/index.html
> +    <script src="js/myLine.js"></script>
update made!

2021-05-19 16:26 UTC, tovarm-uchi commented on public/brush-creator/index.html
> +      </div>
ideally this would be the section to have more tools like shapes and/or changing thickness of stroke, radius etc to give more tools to make the brushes

2021-05-19 16:26 UTC, tovarm-uchi commented on public/brush-creator/index.html
> +          </div>
changes made!

2021-05-19 16:27 UTC, tovarm-uchi commented on public/brush-creator/index.html
> +        <input type="text" id="bname" name="bname" value="Enter Brush Name"><br>
changes made & alert validation added

2021-05-19 16:27 UTC, tovarm-uchi commented on public/brush-creator/index.html
> +      <button id="clear">Clear</button>
change made!

2021-05-19 16:28 UTC, tovarm-uchi commented on public/brush-creator/js/main.js
> +var defaultBrushes = [
brushManager.js made! only question is how to tell the linter that the class is used elsewhere? currently it raises the unused var warning and tried to do the export comment similar global but didn't seem to register

2021-05-19 16:29 UTC, tovarm-uchi commented on public/brush-creator/js/main.js
> +      }
I attempted to make the class standard across all shapes but don't know if it was the best approach since there still seems to be a slight delay

2021-05-19 16:35 UTC, tovarm-uchi commented
> **coding style**: don't forget that we're conforming to the [StandardJS](https://standardjs.com/) coding style. if u haven't already i suggest adding the standard [plugin](https://standardjs.com/#are-there-text-editor-plugins) to ur editor so u can lint ur js files as u work. there are lots of linting/style issues in ur JavaScript files.
   
  I did my best to get away all the lint warnings, however there were a couple I have not been able to address. 
`const create = new p5(createPad, 'create')
const test = new p5(testPad, `'test')`

currently these two lines, no matter the variation I have tried to make it in there is some sort of error. Right now its the unused variable and that p5 should be uppercase but when I remove the variables it says no side effects with just the new and well without the new there is no warning but the canvas are not created. 

> **reorganize code**: u've got global variables being declared throughout ur main.js function, to keep the code a bit more readable it's best to declare all the global variables at the top of the file

I think I addressed this, especially by moving and creating new files 

> **function syntax**: at the moment u're mixing function declaration styles in ur global code. sometimes u do `const name = function ()` other times `function name ()`, both are valid, but for readability it's best to pick one && keep ur code consistent.

I think most of this was also resolved, especially in the new way I declare the createPad and testPad

2021-05-20 21:01 UTC, merged