Merge backend with frontend login page
net-art-uchicago/collaborative-artware pull request #65
Opened 2021-05-27 15:14 UTC by alex-sheen

Updated frontend login page to connect with backend code

2021-06-01 17:05 UTC, nbriz requested changes
i'm still getting lots of errors, so this might need more edits beyond those that i've suggested here (so consider this a start to the review, likely will have more feedback after u make these edits)

in addition to the comments i made below, something else i noticed is that u're saving the entire base64 string to the users's json file, this isn't what we had discussed w/the other groups + as a class (it's also redundant data, b/c the actual image data is already being saved as a png in `user_images/[num]/brushes/[example].png`), so what u want to save in the brushes object's brush key, isn't the data, but rather the path to the png file so instead of this: 
```json
"brushes":[
  {
    "name":"asdf1",
    "brush":"data:image/png;base64,iVBORw0KGgoA...etc"
  }
]
```
it would look like this:
```json
"brushes":[
  {
    "name":"asdf1",
    "brush":"/1/brushes/asdf1.png"
  }
]
```

now, in order for that path to be useful we need to make sure that we are statically serving up the `user_images` directory as we discussed in one of our meetings. this was the main reason we decided to save the images in a separate directory from the `user_data`, in order to do this u need to add the following line somewhere in ur `rest-api.js` file:

```js
router.use(express.static(`${__dirname}/user_images`))
```

2021-06-01 17:05 UTC, nbriz commented on private/rest-api.js
> +  }
there's a couple things u need to address w/these `res.json()` error responses:

first is that when there's an error u should be sending back `res.json({ error: 'some message' })`, like i do in my example, rather than `res.json({ message: 'some message' })`, b/c by differentiating between the `error` key && `mesage` key it will become easier for the font-end to know whether the json returned was an error or not by simply checking `if (json.error)`

the other thing u need to do is `return res.json()`, like i do in my example, including the `return` keyword will exit the function at this point && ensure that the code below doesn't attempt to run (w/out these `return` statements, the code will keep running after we send the response which will inevitably cause errors)

make sure u make these changes for the other error responses below this point as well

2021-06-01 17:05 UTC, nbriz commented on public/brush-creator/js/main.js
> +
we want to avoid attaching functions to the p5 instance that it doesn't expect. it's expecting things like `setup` && `draw` (that's part of the library) but it's not expecting us to create a `fetchBrushes` function, let's write this like this:

```js
function fetchBrushes (p) {
  window.fetch('api/brushdata')
    .then((res) => res.json())
    .then((json) => {
      json.forEach((b) => {
        const newBrushButton = p.createButton(b.name).addClass('premade').id(b.name).parent(p.select('.brushesContainer'))
        bm.addBrush(b.name, b.brush)
        newBrushButton.mousePressed(() => {
          createBrush.updateShape(bm.getBrushDraw(newBrushButton.id()))
          console.log(newBrushButton.id())
        })
      })
    })
}
```
&& place it above/outside of the `const createPad = p => {...`, just like we do w/the `brushPostReq` function.

2021-06-01 17:05 UTC, nbriz commented on public/brush-creator/js/main.js
> +    p.fetchBrushes()
assuming we made the edit i suggested above, this should now be `fetchBrushes(p)`

2021-06-02 01:26 UTC, alex-sheen commented
This PR also adds the backend endpoints for the brush-creation team.

'/brush-creator/api/brushdata' returns the user's brushes

'/brush-creator/api/newbrush' adds a new brush to the user's files

2021-06-02 20:43 UTC, nbriz commented
rad, everything looks + works great, feel free to merge :)

2021-06-02 20:44 UTC, merged