Re-opened pull request for sound in whiteboard
net-art-uchicago/collaborative-artware pull request #73
Opened 2021-05-29 23:41 UTC by navila-luna

2021-05-30 22:44 UTC, marcoanaya reviewed
Looks good and functional to me. Seems like its integrated into the tool bar Hailey made, and with a similar approach/style

2021-05-31 22:21 UTC, nbriz requested changes
everything looks good to me, except for the couple of comments i made below (the second one being most important), after u address those feel free to merge!

2021-05-31 22:21 UTC, nbriz commented on public/index.html
> +    <script src="../js/libs/p5.min.js"></script>
did u mean to add this here? don't think it's necessary.

2021-05-31 22:21 UTC, nbriz commented on public/whiteboard/index.html
> +    <script src="js/YTSampler.js" ></script>
this is looking for a file called `YTSampler.js` (capital "S"), but ur file is actually called `YTsampler.js` (lower case "s"), so the js file isn't actually getting loaded up for me. i was able to change the name locally to test if it works (&& it does! solid job!) but i wonder how u got it to work on ur end w/the mis-matched file names? maybe u've got a local commit u haven't pushed yet?

2021-06-01 00:26 UTC, merged